Revert "dataset .dvc files"
iterative/dataset-registry pull request #36
Opened 2022-12-19 08:57 UTC by SoyGema

Reverts iterative/dataset-registry#33
Last commit wasn´t included

2022-12-19 09:58 UTC, SoyGema commented
- [X] Add README.md 
- [X] Remove unnecessary .dvc file

2022-12-19 10:02 UTC, SoyGema commented
- [X] Remove .gitignore root folder.

2022-12-19 18:44 UTC, shcheklein commented on workshop/README.md
> +## Dataset description
I think we need primarily some info on where this dataset is being used, if it's from Kaggle and structure is described there - no need to repeat much tbh.

Also, please try to wrap it at 80 like we do in the other projects - docs, blog, etc.

2022-12-19 18:44 UTC, shcheklein requested changes
Thanks @SoyGema ! A small stylistic comment.

2022-12-19 18:45 UTC, shcheklein commented
> * [x]  Remove .gitignore root folder.

I don't see any changes to it? Expected?

2022-12-20 15:25 UTC, shcheklein commented on workshop/README.md
> +Dataset published in [Kaggle](https://www.kaggle.com/datasets/idawoodjee/predict-the-positions-and-speeds-of-600-satellites) and has been collected by
same here, please format

there are plugins for VS Code that can do wrap automatically - e.g. https://marketplace.visualstudio.com/items?itemName=stkb.rewrap

2022-12-21 18:01 UTC, shcheklein commented on workshop/README.md
> +
@SoyGema extra space are not needed

2022-12-22 21:04 UTC, shcheklein approved these changes
Thanks @SoyGema ! :)

2022-12-22 21:04 UTC, merged